language: java
arch: amd64
os: linux
dist: focal
services:
- docker
after_script:
- docker build -t carstenmichel/sbadd:latest .

deploy:
  provider: script
  script: docker_push
  on:
    branch: master
env:
  global:
  - secure: e2+2kfMou6SDsM7VujvxUHrNK/CjMGG+glrAdqw+ih1jinwP+qMxOEST0sUC/hCGDC0GwPyXefDEcsKvM7drxG/yTjl7cdallfHX0aORIKPgppFC78JlZlN+TH61LCWqXhUAWa5nQjCngE6oEh3j5jv7sN5abMcQP5tSX/f1T9L6tYSqseMPUXtEnYtb2gUJ63dyxBbezr2R1OV0kKhTjjdq5PaZPCXtqIxUwkc2gaoFgI6de9B+JKYtyiH7u7CxBhgflejpIMUDWsUGC2FwPA9M8cMJnIR7zm4smbUpc8wdNJm8k6nUn1K38tajYMxyCy1dasY/DHKOGu4OSM/CH4/9hfisY7MFH9pkBe08zAsa5Y6jTifQS2MZ9y8AmXbdv5NRF8kzu1lzDmZht3zsQLhYJULzZYOxBY7VJNx49kJ8K0xbnN3IxFW2x/5vPgJLPfBLemhR8YgjJkahcpPxZoMBmldeq5hq/ZL4RaSZqfAGInoUnnEQvqO+O0f33YwW71TrpNKKn717hslVe3XU9UPDtR3Bsn33LVBgLLxIT4XAj11n17ODMxKCtgqKtzV2c1mT030zGIiDVLwD7BF7x/HlxUzheArcNNfIa7no18SM995Oh/hsiRU0OiBS3BRJAuXG6lEQyvLJw+FvpHL2yjyGprrDPT6Bzx5mYjjOVeY=
  - secure: nWLykj7w9PqxBbfZYHCsycZBqS5eyyHxrn3r2g0gjXn6VEBHs85vUCaMqbxt1jAKK/qgjhAKD/C1OrsRahf+QjKh0+/HGJtalSlzx+QgMlB2szf2DkNHG6Vdg8pEXm4TGuqVLrPYydq+xUIZ+T79r3ElfLAxmRA+Yqpi6AKftPYJi40DHSRr03FjoT1K86xh/Q3Dz/kLKRAiAx8YwNdNc1xEaZdlTyX0Z4a7E9CvMBzcc0dP9c93gEbyNePZSyCEo5d9PPfBxt+RCkW6zgkUFIumDAezh9EHAmlpxw0yfXjnfcE07muRiH9g5txgv7JjtMa/rS42Gy3X4RhlfFHWhM2BauYTyeCDhED+GVqQaROsj4eTIQ2xp65iEDPGu3SrB/mtGHkYfVPhz59z6pnGa20/gzshnLlPuXxfCVXOtFLtNWyrJkv8Usd9kr0SWKMPs4qnxdKK4JTwezyzkTepzRPqaI0f1JmN02HQDVV+x7T+00uTjtU5umjBVpz9+35mf0ZSfd8NKH1Ej5rtPr3SxTOihRyR5HfwE34q0Aq24a8xsgvhQq/IubLXrid64+Bkdr1RLRI7YGMesllSIN6ksXy1s+kw7SqFAEGc23LL/QcfAjXl03SwOJ7wrwe5kAyCUNxG9kZxTGa6g08lKpzsPPdsNgOe+96oU/pLrolFwfQ=
